# Generated by Django 6.0.4 on 2026-04-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioerp',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de empleado'),
        ),
        migrations.AddField(
            model_name='usuarioerp',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
