# Generated by Django 6.0.4 on 2026-04-10 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0003_departamento_usuarioerp_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarioerp',
            options={'verbose_name': 'Usuario ERP', 'verbose_name_plural': 'Usuarios ERP'},
        ),
        migrations.AddField(
            model_name='usuarioerp',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='usuarioerp',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioerp',
            name='fecha_ultima_sesion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sesión'),
        ),
        migrations.AlterField(
            model_name='usuarioerp',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número de empleado'),
        ),
    ]
