# Generated by Django 6.0.4 on 2026-04-10 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0006_rename_calidad_to_qa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de recepción')),
                ('hora_recepcion', models.TimeField(verbose_name='Hora de recepción')),
                ('proveedor', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('orden_compra', models.CharField(blank=True, max_length=80, verbose_name='Orden de compra')),
                ('factura', models.CharField(blank=True, max_length=80, verbose_name='Factura / Remisión')),
                ('transportista', models.CharField(blank=True, max_length=200, verbose_name='Transportista')),
                ('placas', models.CharField(blank=True, max_length=30, verbose_name='Placas de unidad')),
                ('chk_oc', models.BooleanField(default=False)),
                ('chk_cantidad', models.BooleanField(default=False)),
                ('chk_empaque', models.BooleanField(default=False)),
                ('chk_lote', models.BooleanField(default=False)),
                ('chk_vigencia', models.BooleanField(default=False)),
                ('chk_certificado', models.BooleanField(default=False)),
                ('chk_estado_fisico', models.BooleanField(default=False)),
                ('chk_foto', models.BooleanField(default=False)),
                ('chk_calidad', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('accion_recomendada', models.CharField(blank=True, choices=[('ACEPTAR_TODO', 'Aceptar todo el embarque'), ('ACEPTAR_PARCIAL', 'Aceptar parcial y levantar incidencia'), ('RECHAZAR', 'Rechazar embarque'), ('CUARENTENA', 'Cuarentena para revisión de calidad')], max_length=30, verbose_name='Acción recomendada')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada')], default='ENVIADA', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_material', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de material',
                'verbose_name_plural': 'Recepciones de material',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('um', models.CharField(blank=True, max_length=20, verbose_name='Unidad de medida')),
                ('cantidad_oc', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad OC')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad recibida')),
                ('lote', models.CharField(blank=True, max_length=80)),
                ('ubicacion_destino', models.CharField(blank=True, max_length=80)),
                ('estatus', models.CharField(choices=[('ACEPTADO', 'Aceptado'), ('DIFERENCIA', 'Diferencia'), ('RECHAZADO', 'Rechazado')], default='ACEPTADO', max_length=12)),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='autenticacion.recepcionmaterial')),
            ],
            options={
                'verbose_name': 'Detalle de recepción',
                'verbose_name_plural': 'Detalles de recepción',
            },
        ),
    ]
