# Generated by Django 6.0.4 on 2026-04-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0008_material_recepcionmaterialdetalle_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
