# Generated by Django 6.0.4 on 2026-04-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0010_proveedor_recepcionmaterial_proveedor_registrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='materiales',
            field=models.ManyToManyField(blank=True, help_text='Materiales que suministra este proveedor', to='autenticacion.material', verbose_name='Materiales'),
        ),
    ]
