# Generated by Django 6.0.4 on 2026-04-10 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0011_proveedor_materiales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='InventarioAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Stock actual')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_material', to='autenticacion.almacen')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios_almacen', to='autenticacion.material')),
            ],
            options={
                'verbose_name': 'Inventario por almacen',
                'verbose_name_plural': 'Inventario por almacen',
                'ordering': ['almacen__codigo', 'material__sku'],
                'constraints': [models.UniqueConstraint(fields=('material', 'almacen'), name='unique_material_almacen')],
            },
        ),
    ]
