# Generated by Django 6.0.4 on 2026-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0012_almacen_inventarioalmacen'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventarioalmacen',
            name='unique_material_almacen',
        ),
        migrations.AddField(
            model_name='inventarioalmacen',
            name='lote',
            field=models.CharField(blank=True, max_length=80, verbose_name='Lote'),
        ),
        migrations.AddConstraint(
            model_name='inventarioalmacen',
            constraint=models.UniqueConstraint(fields=('material', 'almacen', 'lote'), name='unique_material_almacen_lote'),
        ),
    ]
