# Generated by Django 6.0.4 on 2026-04-13 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0013_remove_inventarioalmacen_unique_material_almacen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de salida')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('linea_destino', models.CharField(max_length=120, verbose_name='Linea destino')),
                ('orden_produccion', models.CharField(blank=True, max_length=80, verbose_name='Orden de produccion')),
                ('turno', models.CharField(blank=True, max_length=40, verbose_name='Turno')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_linea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida a linea',
                'verbose_name_plural': 'Salidas a linea',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SalidaLineaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('um', models.CharField(blank=True, max_length=20, verbose_name='Unidad de medida')),
                ('cantidad_enviada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad enviada')),
                ('lote', models.CharField(blank=True, max_length=80)),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_detalle', to='autenticacion.almacen')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_detalle', to='autenticacion.material')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='autenticacion.salidalinea')),
            ],
            options={
                'verbose_name': 'Detalle salida a linea',
                'verbose_name_plural': 'Detalles salida a linea',
            },
        ),
    ]
