# Generated by Django 6.0.4 on 2026-04-13 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0014_salidalinea_salidalineadetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transferencia', models.DateField(verbose_name='Fecha de transferencia')),
                ('hora_transferencia', models.TimeField(verbose_name='Hora de transferencia')),
                ('referencia', models.CharField(blank=True, max_length=80, verbose_name='Referencia')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='autenticacion.almacen')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='autenticacion.almacen')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_almacen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia entre almacenes',
                'verbose_name_plural': 'Transferencias entre almacenes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaAlmacenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('um', models.CharField(blank=True, max_length=20, verbose_name='Unidad de medida')),
                ('cantidad_transferida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad transferida')),
                ('lote', models.CharField(blank=True, max_length=80)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_detalle', to='autenticacion.material')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='autenticacion.transferenciaalmacen')),
            ],
            options={
                'verbose_name': 'Detalle transferencia entre almacenes',
                'verbose_name_plural': 'Detalles transferencia entre almacenes',
            },
        ),
    ]
