# Generated by Django 5.2.13 on 2026-05-01 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0018_bom_bomdetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True, verbose_name='Folio')),
                ('cantidad_planificada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad a producir')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin estimada')),
                ('linea_produccion', models.CharField(blank=True, max_length=120, verbose_name='Línea de producción')),
                ('turno', models.CharField(blank=True, max_length=40, verbose_name='Turno')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=12, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_produccion', to='autenticacion.bom', verbose_name='BOM / Producto')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de producción',
                'verbose_name_plural': 'Planes de producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PlanProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad requerida')),
                ('cantidad_disponible', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad disponible en inventario')),
                ('cantidad_faltante', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad faltante (a comprar)')),
                ('estado_material', models.CharField(choices=[('DISPONIBLE', 'Disponible en inventario'), ('PARCIAL', 'Stock parcial'), ('REQUIERE_COMPRA', 'Requiere orden de compra')], default='DISPONIBLE', max_length=20, verbose_name='Estado de material')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_produccion_detalles', to='autenticacion.material')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='autenticacion.planproduccion')),
            ],
            options={
                'verbose_name': 'Detalle plan de producción',
                'verbose_name_plural': 'Detalles plan de producción',
                'ordering': ['material__sku'],
            },
        ),
    ]
