# Generated by Django 5.2.13 on 2026-05-01 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0019_planproduccion_planproducciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='tipo',
            field=models.CharField(choices=[('MATERIALES', 'Materiales'), ('MFG', 'Fabricación (MFG)')], default='MATERIALES', max_length=12, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='BOMOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.PositiveSmallIntegerField(default=1, verbose_name='Secuencia')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre de operación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('linea_produccion', models.CharField(blank=True, max_length=120, verbose_name='Línea de producción')),
                ('tiempo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiempo estimado')),
                ('unidad_tiempo', models.CharField(choices=[('min', 'Minutos'), ('hrs', 'Horas'), ('seg', 'Segundos')], default='min', max_length=4, verbose_name='Unidad de tiempo')),
                ('recurso_maquina', models.CharField(blank=True, max_length=120, verbose_name='Máquina / Equipo')),
                ('operadores_requeridos', models.PositiveSmallIntegerField(default=1, verbose_name='Operadores requeridos')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='autenticacion.bom')),
            ],
            options={
                'verbose_name': 'Operación BOM',
                'verbose_name_plural': 'Operaciones BOM',
                'ordering': ['bom', 'secuencia'],
                'constraints': [models.UniqueConstraint(fields=('bom', 'secuencia'), name='unique_bom_secuencia')],
            },
        ),
    ]
