# Generated by Django 5.2.13 on 2026-05-02 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0020_bom_tipo_bomoperacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoMaterialProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True, verbose_name='Folio')),
                ('cantidad_planificada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad a producir')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADO_FINANZAS', 'Enviado a finanzas')], default='BORRADOR', max_length=18, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio_finanzas', models.DateTimeField(blank=True, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_materiales', to='autenticacion.bom', verbose_name='BOM / Producto')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_materiales_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento de material de producción',
                'verbose_name_plural': 'Requerimientos de material de producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoMaterialProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base_requerida', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad base requerida')),
                ('cantidad_con_scrap', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad con scrap')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock actual')),
                ('cantidad_sugerida_compra', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad sugerida compra')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad solicitada')),
                ('observaciones', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos_produccion_detalle', to='autenticacion.material')),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='autenticacion.requerimientomaterialproduccion')),
            ],
            options={
                'verbose_name': 'Detalle requerimiento material producción',
                'verbose_name_plural': 'Detalles requerimiento material producción',
                'ordering': ['material__sku'],
                'constraints': [models.UniqueConstraint(fields=('requerimiento', 'material'), name='unique_req_produccion_material')],
            },
        ),
    ]
