# Generated by Django 6.0.4 on 2026-05-04 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0021_requerimientomaterialproduccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True, verbose_name='Folio')),
                ('cantidad_planificada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad planificada')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad producida real')),
                ('linea_produccion', models.CharField(blank=True, max_length=120, verbose_name='Línea de producción')),
                ('turno', models.CharField(blank=True, max_length=60, verbose_name='Turno')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROCESO', 'En proceso'), ('PAUSADA', 'Pausada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=12, verbose_name='Estado')),
                ('fecha_inicio_programada', models.DateField(blank=True, null=True, verbose_name='Fecha inicio programada')),
                ('fecha_fin_programada', models.DateField(blank=True, null=True, verbose_name='Fecha fin programada')),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Inicio real')),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True, verbose_name='Fin real')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_fabricacion', to='autenticacion.bom', verbose_name='BOM / Producto')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_fabricacion', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_fabricacion', to='autenticacion.planproduccion', verbose_name='Plan de producción')),
            ],
            options={
                'verbose_name': 'Orden de fabricación',
                'verbose_name_plural': 'Órdenes de fabricación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenFabricacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad requerida')),
                ('cantidad_consumida', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad consumida real')),
                ('observaciones', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_fabricacion_detalle', to='autenticacion.material')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='autenticacion.ordenfabricacion')),
            ],
            options={
                'verbose_name': 'Detalle orden de fabricación',
                'verbose_name_plural': 'Detalles orden de fabricación',
                'ordering': ['material__sku'],
                'constraints': [models.UniqueConstraint(fields=('orden', 'material'), name='unique_of_material')],
            },
        ),
    ]
