# Generated by Django 6.0.4 on 2026-05-04 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0022_ordenfabricacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True, verbose_name='Folio')),
                ('fecha_captura', models.DateField(verbose_name='Fecha de captura')),
                ('hora_captura', models.TimeField(verbose_name='Hora de captura')),
                ('linea_produccion', models.CharField(blank=True, max_length=120, verbose_name='Línea de producción')),
                ('turno', models.CharField(blank=True, max_length=60, verbose_name='Turno')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad producida')),
                ('operador', models.CharField(blank=True, max_length=200, verbose_name='Operador / Responsable')),
                ('estado', models.CharField(choices=[('CAPTURADO', 'Capturado'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='CAPTURADO', max_length=12, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='autenticacion.bom', verbose_name='Producto (BOM)')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to=settings.AUTH_USER_MODEL)),
                ('orden_fabricacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='autenticacion.ordenfabricacion', verbose_name='Orden de fabricación')),
            ],
            options={
                'verbose_name': 'Lote de producción',
                'verbose_name_plural': 'Lotes de producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
