# Generated by Django 5.2.13 on 2026-05-26 04:42

import django.db.models.deletion
from django.db import migrations, models


def seed_it_and_clientes(apps, schema_editor):
    Departamento = apps.get_model('autenticacion', 'Departamento')
    ClienteCompra = apps.get_model('autenticacion', 'ClienteCompra')

    Departamento.objects.get_or_create(
        nombre='IT',
        defaults={
            'descripcion': 'Administracion de catalogos maestros y soporte a integraciones operativas',
            'activo': True,
        },
    )

    clientes = [
        {
            'codigo': 'CLI-LG',
            'nombre': 'LG Electronics Mexico',
            'contacto': 'Cuenta corporativa LG',
            'email': 'compras.lg@cliente.local',
            'telefono': '55-1000-0001',
        },
        {
            'codigo': 'CLI-SAM',
            'nombre': 'Samsung Electronics Mexico',
            'contacto': 'Cuenta corporativa Samsung',
            'email': 'compras.samsung@cliente.local',
            'telefono': '55-1000-0002',
        },
        {
            'codigo': 'CLI-WHM',
            'nombre': 'Whirlpool Mexico',
            'contacto': 'Cuenta corporativa Whirlpool',
            'email': 'compras.whirlpool@cliente.local',
            'telefono': '55-1000-0003',
        },
        {
            'codigo': 'CLI-HIS',
            'nombre': 'Hisense Mexico',
            'contacto': 'Cuenta corporativa Hisense',
            'email': 'compras.hisense@cliente.local',
            'telefono': '55-1000-0004',
        },
        {
            'codigo': 'CLI-MAB',
            'nombre': 'Mabe',
            'contacto': 'Cuenta corporativa Mabe',
            'email': 'compras.mabe@cliente.local',
            'telefono': '55-1000-0005',
        },
    ]

    for cliente in clientes:
        ClienteCompra.objects.update_or_create(
            codigo=cliente['codigo'],
            defaults={
                'nombre': cliente['nombre'],
                'contacto': cliente['contacto'],
                'email': cliente['email'],
                'telefono': cliente['telefono'],
                'activo': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0024_reclamocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('contacto', models.CharField(blank=True, max_length=150, verbose_name='Contacto principal')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente de compra',
                'verbose_name_plural': 'Clientes de compra',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='loteproduccion',
            name='cliente_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='autenticacion.clientecompra', verbose_name='Cliente destino'),
        ),
        migrations.AddField(
            model_name='reclamocliente',
            name='cliente_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamos_cliente', to='autenticacion.clientecompra', verbose_name='Cliente catálogo'),
        ),
        migrations.RunPython(seed_it_and_clientes, migrations.RunPython.noop),
    ]
