# Generated by Django 5.2.13 on 2026-05-26 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0025_clientecompra_loteproduccion_cliente_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteKPIProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio reporte')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin reporte')),
                ('disponibilidad', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Disponibilidad')),
                ('rendimiento', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Rendimiento')),
                ('calidad', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Calidad')),
                ('oee', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='OEE')),
                ('tiempo_ciclo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tiempo de ciclo promedio')),
                ('tasa_rechazo', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Tasa de rechazo')),
                ('cumplimiento_ordenes', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Cumplimiento de órdenes')),
                ('costo_planificado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo planificado')),
                ('costo_real', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo real')),
                ('variacion_costos', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Variación de costos')),
                ('utilizacion_maquinas', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Utilización de máquinas')),
                ('utilizacion_personal', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Utilización de personal')),
                ('utilizacion_recursos', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Utilización de recursos')),
                ('alertas', models.JSONField(blank=True, default=list, verbose_name='Alertas')),
                ('detalle', models.JSONField(blank=True, default=dict, verbose_name='Detalle')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_kpi_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte KPI de producción',
                'verbose_name_plural': 'Reportes KPI de producción',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
