# Generated by Django 5.2.13 on 2026-05-26 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0026_reportekpiproduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoHoraMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_produccion', models.CharField(max_length=120, verbose_name='Línea de producción')),
                ('maquina_nombre', models.CharField(max_length=150, verbose_name='Máquina / Equipo')),
                ('costo_hora', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo hora real')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_maquina_actualizados', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_maquina_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Costo hora máquina',
                'verbose_name_plural': 'Costos hora de máquina',
                'ordering': ['linea_produccion', 'maquina_nombre'],
            },
        ),
        migrations.CreateModel(
            name='CostoHoraOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomina_hora', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Nómina por hora')),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Asistencia %')),
                ('factor_desempeno', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Desempeño %')),
                ('costo_hora_real', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo hora real')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_operador_actualizados', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_hora_operador', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_operador_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Costo hora operador',
                'verbose_name_plural': 'Costos hora de operador',
                'ordering': ['operador__username'],
            },
        ),
        migrations.CreateModel(
            name='RegistroScrapDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_defectos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad defectos')),
                ('tipo_defecto', models.CharField(choices=[('SCRAP', 'Scrap'), ('VISUAL', 'Defecto visual'), ('FUNCIONAL', 'Defecto funcional'), ('DIMENSIONAL', 'Defecto dimensional'), ('PROCESO', 'Defecto de proceso')], max_length=20, verbose_name='Tipo de defecto')),
                ('causa', models.CharField(max_length=150, verbose_name='Causa')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scraps_actualizados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraps_defectos', to='autenticacion.loteproduccion')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraps_defectos', to='autenticacion.ordenfabricacion')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scraps_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro scrap / defecto',
                'verbose_name_plural': 'Registros scrap / defectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InformeValidacionDefectoQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_validacion', models.CharField(choices=[('EN_ANALISIS', 'En análisis'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='EN_ANALISIS', max_length=15, verbose_name='Resultado validación')),
                ('falla_maquina', models.BooleanField(default=False, verbose_name='Falla de máquina')),
                ('informe', models.TextField(verbose_name='Informe QA')),
                ('acciones_contencion', models.TextField(blank=True, verbose_name='Acciones de contención')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('validado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informes_defectos_qa', to=settings.AUTH_USER_MODEL)),
                ('defecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_qa', to='autenticacion.registroscrapdefecto')),
            ],
            options={
                'verbose_name': 'Informe validación defecto QA',
                'verbose_name_plural': 'Informes de validación de defectos QA',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroUsoRecursoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_recurso', models.CharField(choices=[('MAQUINA', 'Máquina'), ('OPERADOR', 'Operador')], max_length=12, verbose_name='Tipo recurso')),
                ('horas_reales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas reales')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo total')),
                ('notas', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_recurso_actualizados', to=settings.AUTH_USER_MODEL)),
                ('costo_maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_orden', to='autenticacion.costohoramaquina')),
                ('costo_operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_orden', to='autenticacion.costohoraoperador')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_recursos', to='autenticacion.ordenfabricacion')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_recurso_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de recurso de producción',
                'verbose_name_plural': 'Usos de recursos de producción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='costohoramaquina',
            constraint=models.UniqueConstraint(fields=('linea_produccion', 'maquina_nombre'), name='unique_linea_maquina_costo'),
        ),
        migrations.AddConstraint(
            model_name='costohoraoperador',
            constraint=models.UniqueConstraint(fields=('operador',), name='unique_operador_costo_hora'),
        ),
    ]
