# Generated by Django 5.2.8 on 2026-05-27 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0028_costeoproduccion_cuentacontable_cuentaporpagarcobrar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='creada_desde_mfg',
            field=models.BooleanField(default=False, verbose_name='Creada desde requerimiento MFG'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='requerimiento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_generadas', to='autenticacion.requerimientomaterialproduccion'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='tiempo_entrega_estimado_dias',
            field=models.PositiveIntegerField(default=0, verbose_name='Tiempo estimado entrega (días)'),
        ),
    ]
