from django.urls import path
from .views import (
    bom_lista_materiales,
    bom_mfg,
    control_recursos_mfg,
    finanzas_contabilidad,
    finanzas_costeo_produccion,
    finanzas_dashboard,
    finanzas_impuestos,
    finanzas_ordenes_compra,
    finanzas_pagos_cobros,
    finanzas_presupuestos,
    finanzas_reportes,
    indicadores_kpis_mfg,
    planificacion_produccion,
    requerimiento_materiales_produccion,
    ordenes_fabricacion,
    plan_produccion_diario,
    captura_lotes,
    escaneo_produccion,
    login_usuario,
    register_usuario,
    home,
    logout_usuario,
    perfil_usuario,
    entrada_material_planta,
    entrada_material_linea,
    ordenes_compra,
    proveedores_alta,
    transferencia_almacenes,
    historial_recepciones,
    historial_almacen,
    inventario_almacen,
    it_bitacora,
    it_clientes_compra,
    it_soporte,
    it_usuarios,
    calidad_inspeccion_material,
    qa_sqa,
    qa_oqa,
    qa_customer_service,
    qa_qqa_defectos,
    api_materiales_proveedor,
)

urlpatterns = [
    path('login/', login_usuario, name='login'),
    path('register/', register_usuario, name='register'),
    path('home/', home, name='home'),
    path('logout/', logout_usuario, name='logout'),
    path('perfil/', perfil_usuario, name='perfil'),
    path('inventario/entrada-planta/', entrada_material_planta, name='entrada_planta'),
    path('inventario/entrada-linea/', entrada_material_linea, name='entrada_linea'),
    path('inventario/bom/', bom_lista_materiales, name='bom_lista_materiales'),
    path('inventario/ordenes-compra/', ordenes_compra, name='ordenes_compra'),
    path('inventario/proveedores/', proveedores_alta, name='proveedores_alta'),
    path('inventario/transferencias-almacenes/', transferencia_almacenes, name='transferencias_almacenes'),
    path('inventario/historial-recepciones/', historial_recepciones, name='historial_recepciones'),
    path('inventario/historial-almacen/', historial_almacen, name='historial_almacen'),
    path('inventario/almacen/', inventario_almacen, name='inventario_almacen'),
    path('it/usuarios/', it_usuarios, name='it_usuarios'),
    path('it/bitacora/', it_bitacora, name='it_bitacora'),
    path('it/soporte/', it_soporte, name='it_soporte'),
    path('it/clientes-compra/', it_clientes_compra, name='it_clientes_compra'),
    path('finanzas/dashboard/', finanzas_dashboard, name='finanzas_dashboard'),
    path('finanzas/contabilidad/', finanzas_contabilidad, name='finanzas_contabilidad'),
    path('finanzas/presupuestos/', finanzas_presupuestos, name='finanzas_presupuestos'),
    path('finanzas/pagos-cobros/', finanzas_pagos_cobros, name='finanzas_pagos_cobros'),
    path('finanzas/costeo-produccion/', finanzas_costeo_produccion, name='finanzas_costeo_produccion'),
    path('finanzas/reportes/', finanzas_reportes, name='finanzas_reportes'),
    path('finanzas/impuestos/', finanzas_impuestos, name='finanzas_impuestos'),
    path('finanzas/ordenes-compra/', finanzas_ordenes_compra, name='finanzas_ordenes_compra'),
    path('calidad/inspeccion-material/', calidad_inspeccion_material, name='calidad_inspeccion'),
    path('qa/sqa/', qa_sqa, name='qa_sqa'),
    path('qa/oqa/', qa_oqa, name='qa_oqa'),
    path('qa/qqaat-defectos/', qa_qqa_defectos, name='qa_qqa_defectos'),
    path('qa/customer-service/', qa_customer_service, name='qa_customer_service'),
    path('api/materiales-proveedor/<int:proveedor_id>/', api_materiales_proveedor, name='api_materiales_proveedor'),
    path('produccion/planificacion/', planificacion_produccion, name='planificacion_produccion'),
    path('produccion/requerimiento-materiales/', requerimiento_materiales_produccion, name='requerimiento_materiales_produccion'),
    path('produccion/bom-mfg/', bom_mfg, name='bom_mfg'),
    path('produccion/control-recursos/', control_recursos_mfg, name='control_recursos_mfg'),
    path('produccion/indicadores-kpis/', indicadores_kpis_mfg, name='indicadores_kpis_mfg'),
    path('produccion/plan-diario/', plan_produccion_diario, name='plan_produccion_diario'),
    path('produccion/ordenes-fabricacion/', ordenes_fabricacion, name='ordenes_fabricacion'),
    path('produccion/captura-lotes/', captura_lotes, name='captura_lotes'),
    path('produccion/escaneo/', escaneo_produccion, name='escaneo_produccion'),
]
